import type { QuestMeta as SharedQuestMeta } from "@/lib/learn/types";

export type QuestMeta = SharedQuestMeta & { region: "Kanto" | "Johto" };

export const quests: QuestMeta[] = [
  {
    slug: "quest-1",
    title: "Understanding Partition Keys",
    subtitle:
      "Learn how DynamoDB decides where items live and why partition keys keep related Pokémon together.",
    accentColor: "#FF8CBA",
    accentForegroundColor: "#FFFFFF",
    topics: ["Primary keys", "Hashing", "Data locality"],
    status: "available",
    region: "Kanto",
    difficulty: "Beginner",
    duration: "12 min",
  },
  {
    slug: "quest-2",
    title: "Simple Primary Key in Action",
    subtitle:
      "Build a table that stores Pokémon by name, then insert and retrieve data using a simple primary key.",
    accentColor: "#92FDF2",
    accentForegroundColor: "#FFFFFF",
    topics: ["Table design", "PutItem", "GetItem"],
    status: "available",
    region: "Kanto",
    difficulty: "Beginner",
    duration: "15 min",
  },
  {
    slug: "quest-3",
    title: "Fetch All Pokémon",
    subtitle:
      "Learn when a full-table Scan is acceptable, what it costs, and how to paginate every 1 MB response safely.",
    accentColor: "#FFE066",
    accentForegroundColor: "#FFFFFF",
    topics: ["Scan", "1 MB pages", "Read cost"],
    status: "available",
    region: "Kanto",
    difficulty: "Beginner",
    duration: "14 min",
  },
  {
    slug: "quest-4",
    title: "Get Your Starter Pokémon",
    subtitle:
      "Fetch the perfect partner Pokémon with a single GetItem request, using its exact primary key.",
    accentColor: "#FFB8D2",
    accentForegroundColor: "#FFFFFF",
    topics: ["GetItem", "Primary-key lookup", "Read consistency"],
    status: "available",
    region: "Kanto",
    difficulty: "Beginner",
    duration: "12 min",
  },
  {
    slug: "quest-5",
    title: "Put Mew into Your Party",
    subtitle:
      "Use conditional writes to welcome legendary Pokémon without clobbering existing party data.",
    accentColor: "#B9F5FF",
    accentForegroundColor: "#FFFFFF",
    topics: ["PutItem", "ConditionExpression", "Idempotency"],
    status: "available",
    region: "Kanto",
    difficulty: "Intermediate",
    duration: "16 min",
  },
  {
    slug: "quest-6",
    title: "Update Expression Mastery",
    subtitle:
      "Master UpdateExpression syntax to evolve your Pokémon records safely and predictably.",
    accentColor: "#FFD6A5",
    accentForegroundColor: "#FFFFFF",
    topics: ["UpdateItem", "UpdateExpression", "Attribute paths"],
    status: "available",
    region: "Kanto",
    difficulty: "Intermediate",
    duration: "14 min",
  },
  {
    slug: "quest-7",
    title: "Boost Mew's Stats",
    subtitle:
      "Fine-tune stats with atomic counters so your mythical partner is always battle ready.",
    accentColor: "#C9F0FF",
    accentForegroundColor: "#FFFFFF",
    topics: ["Atomic counters", "Numeric updates", "Consistency"],
    status: "available",
    region: "Kanto",
    difficulty: "Intermediate",
    duration: "14 min",
  },
  {
    slug: "quest-8",
    title: "Release Mew Back to the Wild",
    subtitle:
      "Design safe delete operations that send Pokémon home while protecting the rest of your data.",
    accentColor: "#D8B4FE",
    accentForegroundColor: "#FFFFFF",
    topics: ["DeleteItem", "Conditional deletes", "Soft deletes"],
    status: "available",
    region: "Kanto",
    difficulty: "Intermediate",
    duration: "12 min",
  },
  {
    slug: "quest-expressions",
    title: "Speaking DynamoDB's Language (Expression Attributes)",
    subtitle:
      "Before Johto's advanced patterns, master the two placeholders every expression relies on: ExpressionAttributeValues and ExpressionAttributeNames.",
    accentColor: "#4DD0E1",
    accentForegroundColor: "#FFFFFF",
    topics: ["ExpressionAttributeValues", "ExpressionAttributeNames", "Reserved words"],
    status: "available",
    region: "Johto",
    difficulty: "Intermediate",
    duration: "16 min",
  },
  {
    slug: "quest-9",
    title: "The Johto Pokedex (GSIs)",
    subtitle: "Querying non-primary key attributes efficiently using Global Secondary Indexes without scanning.",
    accentColor: "#81C784",
    accentForegroundColor: "#FFFFFF",
    topics: ["GSI", "Query", "Projection & cost"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "18 min",
  },
  {
    slug: "quest-10",
    title: "Finding the Strongest (Sort Keys)",
    subtitle: "Using Sort Keys in GSIs for ordering and advanced KeyConditionExpressions.",
    accentColor: "#E57373",
    accentForegroundColor: "#FFFFFF",
    topics: ["Sort Keys", "Advanced Querying"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "16 min",
  },
  {
    slug: "quest-11",
    title: "Catching Lugia (Conditional Writes)",
    subtitle: "Use ConditionExpression to prevent duplicate legendary catches and invalid states.",
    accentColor: "#64B5F6",
    accentForegroundColor: "#FFFFFF",
    topics: ["ConditionExpression", "Race safety", "Item existence"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "20 min",
  },
  {
    slug: "quest-12",
    title: "Trading with Rival (Transactions)",
    subtitle: "Execute ACID transactions across multiple items to securely trade Pokémon.",
    accentColor: "#BA68C8",
    accentForegroundColor: "#FFFFFF",
    topics: ["TransactWriteItems", "ACID"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "20 min",
  },
  {
    slug: "quest-13",
    title: "Healing Party (Batch Operations)",
    subtitle: "Fetch multiple Pokémon efficiently, then retry UnprocessedKeys with exponential backoff.",
    accentColor: "#4DB6AC",
    accentForegroundColor: "#FFFFFF",
    topics: ["BatchGetItem", "UnprocessedKeys", "Backoff"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "18 min",
  },
  {
    slug: "quest-14",
    title: "Scrolling the Pokegear (Pagination)",
    subtitle: "Implement pagination using ExclusiveStartKey and LastEvaluatedKey to load lists efficiently.",
    accentColor: "#FFB74D",
    accentForegroundColor: "#FFFFFF",
    topics: ["Pagination", "LastEvaluatedKey"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "15 min",
  },
  {
    slug: "quest-15",
    title: "Burn Heal (Time to Live)",
    subtitle: "Mark temporary status effects for asynchronous TTL cleanup and exclude expired items from application reads.",
    accentColor: "#F06292",
    accentForegroundColor: "#FFFFFF",
    topics: ["TTL", "Asynchronous deletion", "Read filtering"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "16 min",
  },
  {
    slug: "quest-16",
    title: "Elite Four Production Review",
    subtitle: "Turn a working Pokédex into an operable production system by making explicit decisions about scale, recovery, security, and global behavior.",
    accentColor: "#2563EB",
    accentForegroundColor: "#FFFFFF",
    topics: ["Capacity & hot keys", "Streams & PITR", "Security & operations"],
    status: "available",
    region: "Johto",
    difficulty: "Advanced",
    duration: "25 min",
  },
];

export function getQuestMeta(slug: string): QuestMeta | undefined {
  return quests.find(
    (quest) => quest.slug === slug && quest.status === "available",
  );
}

export const availableQuests = quests.filter(
  (quest) => quest.status === "available",
);
